name: Local Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Define global variables here
      IMAGE_NAME: myapp:latest
      TAR_FILE: myapp_latest.tar.gz

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Read custom build-args from file
      - name: Read custom build-args from file
        id: read-build-args
        run: |
          BUILD_ARGS=$(cat build-args.conf | xargs)
          echo "::set-output name=build_args::$BUILD_ARGS"

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build Docker image with custom build-args
      - name: Build Docker image
        run: |
          docker build ${{ steps.read-build-args.outputs.build_args }} -t ${{ env.IMAGE_NAME }} .

      # Step 5: Save Docker image to a .tar.gz file
      - name: Save Docker image to .tar.gz file
        run: |
          docker save ${{ env.IMAGE_NAME }} | gzip > ${{ env.TAR_FILE }}

      # Step 6: Optionally, you can verify the saved image
      - name: Verify saved Docker image
        run: |
          ls -lh ${{ env.TAR_FILE }}
