name: Local Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Define global variables here
      IMAGE_NAME: myapp:latest
      TAR_FILE: myapp_latest.tar.gz

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Read custom build-args from file
      - name: Read custom build-args from file
        id: read-build-args
        run: |
          BUILD_ARGS=$(awk '{print "--build-arg " $0}' build-args.conf)
          echo "BUILD_ARGS=${BUILD_ARGS}" >> $GITHUB_ENV
        shell: bash

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build Docker image with custom build-args
      - name: Build Docker image with custom build-args
        run: |
          docker buildx build ${{ env.BUILD_ARGS }} -t ${{ env.IMAGE_NAME }} .

      # Step 5: Save Docker image to a .tar.gz file
      - name: Save Docker image to .tar.gz file
        run: |
          docker save ${{ env.IMAGE_NAME }} | gzip > ${{ env.TAR_FILE }}

      # Step 6: Optionally, verify the saved image
      - name: Verify saved Docker image
        run: |
          ls -lh ${{ env.TAR_FILE }}
